### ISSUE TITLE
Please make this repo private

### ISSUE THREAD

**Issue by twisted1919** [milicevic79/mailwizz#1]
Hello,

Please make this repo private because right now everyone can download mailwizz for free.  
We'll check back in a few days and if this is still public, we'll fill in a DMCA request with github to take down the repository.

Thank you.

**Comment by milicevic79** [comment]
Hello,

I'm terribly sorry for this inconvenience, I'm removing this repo, and I'm giving you a follow up message with explanation.

Best regards.
